name: Update wakatime metrics to README section

on:
  schedule:
    - cron: '0 */12 * * *'
  workflow_dispatch:
  push:
jobs:
  update-readme:
    name: Update Readme with Metrics
    runs-on: ubuntu-latest
    steps:
      - uses: anmol098/waka-readme-stats@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          SHOW_LOC_CHART: false
          SHOW_SHORT_INFO: false
          SHOW_TIMEZONE: false
          COMMIT_BY_ME: true
          COMMIT_MESSAGE: "chore(metrics): update latest development metrics to readme"
          COMMIT_USERNAME: "@andatoshiki"
          COMMIT_EMAIL: "101481353+andatoshiki@users.noreply.github.com"
          SHOW_LINES_OF_CODE: true
          SHOW_TOTAL_CODE_TIME: true